<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<!-- .NET 9.0でWPFを使用するにはwindows指定が必要 -->
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- WPFを有効にする -->
		<UseWPF>true</UseWPF>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp.Xps" Version="1.0.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

</Project>
